export const GET_PROJECTS = "GET_PROJECTS"
export const REGISTER_PROJECT = "REGISTER_PROJECT"
export const EDIT_PROJECT = "EDIT_PROJECT"
export const REMOVE_PROJECT = "REMOVE_PROJECT"

export const GET_TASKS = "GET_TASKS"
export const REGISTER_TASK = "REGISTER_TASK"
export const EDIT_TASK = "EDIT_TASK"